### PR TITLE
Import Bugfix: avoid dups + ensure root path added

### PR DESCRIPTION
**Pull request by JordanW7**

### CODE REVIEW

**Comment by karlnorling** [comment]
@JordanW7 Is there a way we can add a node implementation that tests this? Like this: https://github.com/redsift/sandbox-python/blob/master/test/server/td/node5.py

**Comment by karlnorling** [comment]
@JordanW7 also we don't have a circleci config for this repo to build and test? Seems it's not required for this repo. I'm not an admin on it, maybe we should be

**Comment by JordanW7** [comment]
> @JordanW7 Is there a way we can add a node implementation that tests this? Like this: https://github.com/redsift/sandbox-python/blob/master/test/server/td/node5.py

I'm not sure how testing works in this repo, or if the issue would be unit testable. I'm guessing we might be able to put a "libs" folder in `test/server` with a `utils.py` file inside it, then try and import this from `/server/td/node5.py`

**Comment by JordanW7** [comment]
Closing. Will reopen in a branch rather than fork.

**Pull request closed without merging**
